### ISSUE TITLE
Setup Saratov repo

### ISSUE THREAD

**Issue by namig** [beerphp/meta#9]
Hi, we want to join :)

Location (city & country): Saratov, Russia
Repo name: beerphp/saratov
Admins (github logins): @namig, @as-sar
Telegram or facebook contacts (optional): @namig_nurmamedov

**Comment by vyants** [comment]
Hi!
Welcome, guys!

Please, contact me in case of any questions!

**Comment by namig** [comment]
@vyants Привет. Не могу запушить в мастер `Permission to beerphp/saratov.git denied to namig`. Можешь добавить меня к репе?

**Comment by vyants** [comment]
@namig я вижу что ты не принял приглашение

<img width="736" alt="Снимок экрана 2019-12-18 в 11 28 51" src="https://user-images.githubusercontent.com/10527620/71069405-b6d6fb80-2189-11ea-9127-dd1f72c7043e.png">

**Comment by namig** [comment]
Сорян, пропустил уведомление. Спасибо!

**Comment by namig** [comment]
Можешь подсказать, есть ли какая-то программа для первой встречи? Чем можно вовлечь народ?
